/**
 * English (United States) - Common Texts
 * Common UI texts: buttons, toasts, placeholders
 */

module.exports = {
  button: {
    confirm: 'Confirm',
    cancel: 'Cancel',
    send: 'Send',
    stop: 'Stop',
    regenerate: 'Regenerate',
    copy: 'Copy',
    like: 'Like',
    dislike: 'Dislike',
    share: 'Share',
    retry: 'Retry',
    ok: 'OK',
    submit: 'Submit',
  },

  toast: {
    sendSuccess: 'Sent successfully',
    sendFailed: 'Failed to send',
    copySuccess: 'Copied successfully',
    copyFailed: 'Failed to copy',
    likeSuccess: 'Liked',
    unlikeSuccess: 'Like removed',
    dislikeSuccess: 'Disliked',
    undislikeSuccess: 'Dislike removed',
    inputRequired: 'Please enter a message',
    networkError: 'Network error, please try again',
    operationSuccess: 'Operation successful',
    operationFailed: 'Operation failed',
    loading: 'Loading...',
    stopSuccess: 'Stopped',
    deleteSuccess: 'Deleted successfully',
    notAvailable: 'Not available',
    filesSelected: '{{count}} file(s) selected',
    clickedFile: 'Clicked {{name}}',
    clickedAddButton: 'Clicked the add button',
    resetSuccess: 'Reset',
  },

  placeholder: {
    inputMessage: 'Type a message...',
    search: 'Search',
    enterContent: 'Enter content',
  },

  status: {
    sending: 'Sending...',
    thinking: 'Thinking...',
    generating: 'Generating...',
    loading: 'Loading...',
  },

  action: {
    delete: 'Delete',
    edit: 'Edit',
    view: 'View',
    download: 'Download',
    upload: 'Upload',
  },

  chatSender: {
    maxHeight: 'Height limit: max height 132px',
    deepThink: 'Deep Thinking',
    aiDisclaimer: 'Content generated by AI, for reference only.',
  },
};
